import { WeatherType, WeatherPreset } from './types';

/** Presets for each weather type — intensity multiplier applied at runtime */
export const WEATHER_PRESETS: Record<WeatherType, WeatherPreset> = {
  [WeatherType.CLEAR]: {
    particleCount: 15,
    wind: { x: 0.05, y: 0, gustStrength: 0.02, gustFrequency: 0.001 },
    ambientTint: 'rgba(0, 0, 0, 0)',
    ambientOpacity: 0,
    particleTypes: ['dust'],
    hasLightning: false,
    hasSunRays: true,
    hasAccumulation: false,
    glassStreaks: false,
    speed: { min: 0.2, max: 0.6 },
    size: { min: 1, max: 3 },
  },
  [WeatherType.DRIZZLE]: {
    particleCount: 60,
    wind: { x: 0.15, y: 0, gustStrength: 0.08, gustFrequency: 0.003 },
    ambientTint: 'rgba(0, 0, 0, 0)',
    ambientOpacity: 0,
    particleTypes: ['rain'],
    hasLightning: false,
    hasSunRays: false,
    hasAccumulation: false,
    glassStreaks: true,
    speed: { min: 4, max: 7 },
    size: { min: 1, max: 2 },
  },
  [WeatherType.RAIN]: {
    particleCount: 180,
    wind: { x: 0.3, y: 0, gustStrength: 0.15, gustFrequency: 0.004 },
    ambientTint: 'rgba(0, 0, 0, 0)',
    ambientOpacity: 0,
    particleTypes: ['rain'],
    hasLightning: false,
    hasSunRays: false,
    hasAccumulation: false,
    glassStreaks: true,
    speed: { min: 8, max: 14 },
    size: { min: 1.5, max: 3 },
  },
  [WeatherType.HEAVY_RAIN]: {
    particleCount: 350,
    wind: { x: 0.5, y: 0, gustStrength: 0.3, gustFrequency: 0.006 },
    ambientTint: 'rgba(0, 0, 0, 0)',
    ambientOpacity: 0,
    particleTypes: ['rain'],
    hasLightning: false,
    hasSunRays: false,
    hasAccumulation: false,
    glassStreaks: true,
    speed: { min: 12, max: 20 },
    size: { min: 2, max: 4 },
  },
  [WeatherType.THUNDERSTORM]: {
    particleCount: 400,
    wind: { x: 0.7, y: 0, gustStrength: 0.5, gustFrequency: 0.008 },
    ambientTint: 'rgba(0, 0, 0, 0)',
    ambientOpacity: 0,
    particleTypes: ['rain'],
    hasLightning: true,
    hasSunRays: false,
    hasAccumulation: false,
    glassStreaks: true,
    speed: { min: 14, max: 22 },
    size: { min: 2, max: 4.5 },
  },
  [WeatherType.SNOW]: {
    particleCount: 120,
    wind: { x: 0.1, y: 0, gustStrength: 0.15, gustFrequency: 0.002 },
    ambientTint: 'rgba(0, 0, 0, 0)',
    ambientOpacity: 0,
    particleTypes: ['snow'],
    hasLightning: false,
    hasSunRays: false,
    hasAccumulation: true,
    glassStreaks: false,
    speed: { min: 0.8, max: 2.5 },
    size: { min: 2.4, max: 6 },
  },
  [WeatherType.BLIZZARD]: {
    particleCount: 360,
    wind: { x: 0.8, y: 0, gustStrength: 0.6, gustFrequency: 0.01 },
    ambientTint: 'rgba(0, 0, 0, 0)',
    ambientOpacity: 0,
    particleTypes: ['snow'],
    hasLightning: false,
    hasSunRays: false,
    hasAccumulation: true,
    glassStreaks: false,
    speed: { min: 2, max: 5 },
    size: { min: 2.4, max: 8 },
  },
  [WeatherType.WIND]: {
    particleCount: 20,
    wind: { x: 1.0, y: 0, gustStrength: 0.8, gustFrequency: 0.012 },
    ambientTint: 'rgba(0, 0, 0, 0)',
    ambientOpacity: 0,
    particleTypes: ['debris'],
    hasLightning: false,
    hasSunRays: false,
    hasAccumulation: false,
    glassStreaks: false,
    speed: { min: 3, max: 8 },
    size: { min: 2, max: 5 },
  },
};

/** Scale preset values by intensity (1-10) */
export const getScaledPreset = (type: WeatherType, intensity: number): WeatherPreset => {
  const base = WEATHER_PRESETS[type];
  const scale = 0.2 + (intensity / 10) * 0.8; // 0.2 at intensity 1, 1.0 at intensity 10
  return {
    ...base,
    particleCount: Math.round(base.particleCount * scale),
    ambientOpacity: base.ambientOpacity * scale,
    wind: {
      ...base.wind,
      x: base.wind.x * scale,
      gustStrength: base.wind.gustStrength * scale,
    },
  };
};
